"""first migration 19-11-2025 20

Revision ID: 8741f5f31fc3
Revises: cc9a60076c31
Create Date: 2025-11-19 00:41:06.969989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8741f5f31fc3'
down_revision: Union[str, Sequence[str], None] = 'cc9a60076c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
